# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/001',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/001',
                'lib_path': '001'},
  'syms': {'001.core': {'001.core.foo': ('core.html#foo', '001/core.py')}}}
